### ISSUE TITLE
Hello，I am very interested in your work, but I got some problem while running this code，could you please give some advice?

### ISSUE THREAD

**Issue by a-little-bit-lazy** [amazon-research/wqa-multi-sentence-inference#1]
When I try to fintune the as2 tasks of wikiqa dataset, I run the bash script of run_roberta_base_joint_ae_k_best.sh,and it goes wrong . the output of error msg is 'to many dimension 'str'',so i m wandering is there some thing i missed to process dataset?

**Comment by lucadiliello** [comment]
Hello @a-little-bit-lazy, thanks for your interest in our project. I cannot reproduce your error. Can you provide additional details and the list of packages versions you are using?

**Comment by a-little-bit-lazy** [comment]
Hi，thanks for replaying，but I figured it out ，nerver mind
